force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>Stores details about ACME bank customers financial accounts</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Financial account number</description>
    <label>Account Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/recordTypes/Spending.recordType-meta.xml
<RecordType>
    <fullName>Spending</fullName>
    <active>true</active>
    <label>Spending</label>
</RecordType>

force-app/main/default/objects/Transaction_History__c/Transaction_History__c.object-meta.xml
<CustomObject>
    <description>Primarily built for storing transaction history for financial accounts</description>
    <label>Transaction History</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_History__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Transaction History</relationshipLabel>
    <relationshipName>Transaction_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TransactionHistoryTriggerHandler.cls
/**
 * @author         : Adnan
 * @date           : 22/02/2021
 * 
 * @group          : TransactionHistoryTriggerHandler
 * @group-content  : ../../ApexDocContent/TransactionHistoryTriggerHandler.htm
 *  
 * @description    : TriggerHandler class for transaction history trigger
 * 
 * @testClass      : TransactionRestResourceTest
 * 
 * @history        : v1.0  22/02/2021 Adnan Initial Version - Developed as part ANZ assessment
 * 
 */
public inherited sharing class TransactionHistoryTriggerHandler {
    public static final String SPENDING = 'Spending';

    /*********************************************************
    * @name         beforeInsertHandler
    * @description  Generaic method for before insert logic
    * @param        List<Transaction_History__c> newTransactions
    * @return       void
    **********************************************************/
    public static void beforeInsertHandler(List<Transaction_History__c> newTransactions){
        updateFinancialAccount(newTransactions);
    }

    /*********************************************************
    * @name         updateFinancialAccount
    * @description  This method contains the logic for updating
                    transactions with their financial accounts
    * @param        List<Transaction_History__c> newTransactions
    * @return       void
    **********************************************************/
    static void updateFinancialAccount(List<Transaction_History__c> newTransactions){
        List<Decimal> accountNosList = new List<Decimal>();
        for(Transaction_History__c trans : newTransactions){
            accountNosList.add(trans.Account_Number__c);
        }

        List<Financial_Account__c> fAccountsList = [Select Id, Name, Account_Number__c from Financial_Account__c where Account_Number__c IN: accountNosList];
        Map<Decimal, Id> accNoWithAccIdMap = new Map<Decimal, Id>();
        if(fAccountsList != null){
            for(Financial_Account__c facc : fAccountsList){
                accNoWithAccIdMap.put(facc.Account_Number__c, facc.Id);
            }
        }

        //Logic for handling transactions with no account number present
        for(Transaction_History__c trans : newTransactions){
            trans.Financial_Account__c = accNoWithAccIdMap.get(trans.Account_Number__c);
            if (trans.Financial_Account__c == null) {
                trans.addError(Label.Financial_Accounts_Error);
            }
        }
    }
}